In [15]:
from pathlib import Path

In [16]:
path = Path('../unlinkability-metric')
path

PosixPath('../unlinkability-metric')

In [17]:
mated_scores = Path(path / 'matedScores.hdf5')
nonmated_scores = Path(path / 'nonMatedScores.hdf5')

In [18]:
mated_scores, nonmated_scores

(PosixPath('../unlinkability-metric/matedScores.hdf5'),
 PosixPath('../unlinkability-metric/nonMatedScores.hdf5'))

In [19]:
import numpy as np
ms = np.fromfile(mated_scores)
nms = np.fromfile(mated_scores)

In [21]:
import pandas as pd

df = pd.DataFrame()
df['ms'] = ms
df['nms'] = nms

In [26]:
df.to_csv('unlinkability_scores.csv')

In [38]:
a = np.linspace(2.0, 3.0, num=5, endpoint=True)
a

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [41]:
a[1:] + a[:-1]

array([4.25, 4.75, 5.25, 5.75])

In [42]:
a[1:]

array([2.25, 2.5 , 2.75, 3.  ])

In [43]:
a[:-1]

array([2.  , 2.25, 2.5 , 2.75])

In [44]:
(a[1:] + a[:-1]) / 2

array([2.125, 2.375, 2.625, 2.875])